[exchange_rates] 
function = "CURRENCY_EXCHANGE_RATE"
[exchange_rates.format]
data_key = "" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[exchange_rates.info]
table = "pair"
collection = "av_exchange_rates"


[forex_intraday] 
function = "FX_INTRADAY"
[forex_intraday.format]
data_key = "Time Series FX (60min)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[forex_intraday.info]
table = "pair"
collection = "av_fx_intraday"


[forex_daily] 
function = "FX_DAILY"
[forex_daily.format]
data_key = "Time Series FX (Daily)" 
first_col = "date"
drop_columns = ["index"]
transpose = false 
reset_index = true
reverse_rows = true
[forex_daily.info]
table = "pair"
collection = "av_fx_daily"


[forex_weekly] 
function = "FX_WEEKLY"
[forex_weekly.format]
data_key = "Time Series FX (Weekly)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[forex_weekly.info]
table = "pair"
collection = "av_fx_weekly"


[forex_monthly] 
function = "FX_MONTHLY"
[forex_monthly.format]
data_key = "Time Series FX (Monthly)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[forex_monthly.info]
table = "pair"
collection = "av_fx_monthly"


[crypto_intraday] 
function = "CRYPTO_INTRADAY"
[crypto_intraday.format]
data_key = "Time Series Crypto (60min)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[crypto_intraday.info]
table = "pair"
collection = "av_crypto_intraday"


[crypto_daily] 
function = "DIGITAL_CURRENCY_DAILY"
[crypto_daily.format]
data_key = "Time Series (Digital Currency Daily)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[crypto_daily.info]
table = "pair"
collection = "av_crypto_daily"


[crypto_weekly] 
function = "DIGITAL_CURRENCY_WEEKLY"
[crypto_weekly.format]
data_key = "Time Series (Digital Currency Weekly)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[crypto_weekly.info]
table = "pair"
collection = "av_crypto_weekly"


[crypto_monthly] 
function = "DIGITAL_CURRENCY_MONTHLY"
[crypto_monthly.format]
data_key = "Time Series (Digital Currency Monthly)" 
first_col = "date"
drop_columns = [] 
transpose = true 
reset_index = true
reverse_rows = true
[crypto_monthly.info]
table = "pair"
collection = "av_crypto_monthly"
