[company_overview] 
function = "OVERVIEW"
[company_overview.format]
data_key = "" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = false
[company_overview.info]
table = "symbol"
collection = "av_company_overview"

[income_statement] 
function = "INCOME_STATEMENT"
[income_statement.format]
data_key = "quarterlyReports" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = true
[income_statement.info]
table = "symbol"
collection = "av_income_statement"


[balance_sheet] 
function = "BALANCE_SHEET"
[balance_sheet.format]
data_key = "quarterlyReports" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = true
[balance_sheet.info]
table = "symbol"
collection = "av_balance_sheet"


[cash_flow] 
function = "CASH_FLOW"
[cash_flow.format]
data_key = "quarterlyReports" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = true
[cash_flow.info]
table = "symbol"
collection = "av_cash_flow"


[earnings] 
function = "EARNINGS"
[earnings.format]
data_key = "quarterlyEarnings" 
first_col = ""
drop_columns = []
transpose = false 
reset_index = false
reverse_rows = true
[earnings.info]
table = "symbol"
collection = "av_earnings"


[listing_delisting] 
function = "LISTING_STATUS"
[listing_delisting.format]
data_key = "" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = false
[listing_delisting.info]
table = "listing_status"
collection = "av_general"


[earnings_calendar]
function = "EARNINGS_CALENDAR"
[earnings_calendar.format]
data_key = "" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = false
[earnings_calendar.info]
table = "earnings_calendar"
collection = "av_general"


[ipo_calendar] 
function = "IPO_CALENDAR"
[ipo_calendar.format]
data_key = "" 
first_col = ""
drop_columns = [] 
transpose = false 
reset_index = false
reverse_rows = false
[ipo_calendar.info]
table = "ipo_calendar"
collection = "av_general"

