[sma] 
function = "SMA"
[sma.format]
data_key = "Technical Analysis: SMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[sma.info]
table = "sma"
collection = "av_technicals"


[ema] 
function = "EMA"
[ema.format]
data_key = "Technical Analysis: EMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ema.info]
table = "ema"
collection = "av_technicals"


[wma] 
function = "WMA"
[wma.format]
data_key = "Technical Analysis: WMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[wma.info]
table = "wma"
collection = "av_technicals"

[dema] 
function = "DEMA"
[dema.format]
data_key = "Technical Analysis: DEMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[dema.info]
table = "dema"
collection = "av_technicals"

[tema] 
function = "tema"
[tema.format]
data_key = "Technical Analysis: TEMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[tema.info]
table = "tema"
collection = "av_technicals"

[trima] 
function = "TRIMA"
[trima.format]
data_key = "Technical Analysis: TRIMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[trima.info]
table = "trima"
collection = "av_technicals"

[kama] 
function = "KAMA"
[kama.format]
data_key = "Technical Analysis: KAMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[kama.info]
table = "kama"
collection = "av_technicals"

[mama] 
function = "MAMA"
[mama.format]
data_key = "Technical Analysis: MAMA" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[mama.info]
table = "mama"
collection = "av_technicals"

[vwap] 
function = "VWAP"
[vwap.format]
data_key = "Technical Analysis: VWAP" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true

[vwap.info]
table = "vwap"
collection = "av_technicals"

[t3] 
function = "T3"
[t3.format]
data_key = "Technical Analysis: T3" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[t3.info]
table = "t3"
collection = "av_technicals"

[macd] 
function = "MACD"
[macd.format]
data_key = "Technical Analysis: MACD" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[macd.info]
table = "macd"
collection = "av_technicals"

[macdext] 
function = "MACDEXT"
[macdext.format]
data_key = "Technical Analysis: MACDEXT" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[macdext.info]
table = "macdext"
collection = "av_technicals"

[stoch]
function = "STOCH"
[stoch.format]
data_key = "Technical Analysis: STOCH" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[stoch.info]
table = "stochastic_oscillator"
collection = "av_technicals"

[stochf] 
function = "STOCHF"
[stochf.format]
data_key = "Technical Analysis: STOCHF" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[stochf.info]
table = "stochf"
collection = "av_technicals"

[rsi] 
function = "RSI"
[rsi.format]
data_key = "Technical Analysis: RSI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[rsi.info]
table = "rsi"
collection = "av_technicals"

[stochrsi] 
function = "STOCHRSI"
[stochrsi.format]
data_key = "Technical Analysis: STOCHRSI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[stochrsi.info]
table = "stochrsi"
collection = "av_technicals"

[willr] 
function = "WILLR"
[willr.format]
data_key = "Technical Analysis: WILLR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[willr.info]
table = "willr"
collection = "av_technicals"

[adx] 
function = "ADX"
[adx.format]
data_key = "Technical Analysis: ADX" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[adx.info]
table = "adx"
collection = "av_technicals"

[adxr] 
function = "ADXR"
[adxr.format]
data_key = "Technical Analysis: ADXR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[adxr.info]
table = "adxr"
collection = "av_technicals"

[apo] 
function = "APO"
[apo.format]
data_key = "Technical Analysis: APO" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[apo.info]
table = "apo"
collection = "av_technicals"

[ppo] 
function = "PPO"
[ppo.format]
data_key = "Technical Analysis: PPO" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ppo.info]
table = "ppo"
collection = "av_technicals"
[ppo.params]

[mom] 
function = "MOM"
[mom.format]
data_key = "Technical Analysis: MOM" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[mom.info]
table = "mom"
collection = "av_technicals"

[bop] 
function = "BOP"
[bop.format]
data_key = "Technical Analysis: BOP" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[bop.info]
table = "bop"
collection = "av_technicals"

[cci] 
function = "CCI"
[cci.format]
data_key = "Technical Analysis: CCI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[cci.info]
table = "cci"
collection = "av_technicals"

[cmo] 
function = "CMO"
[cmo.format]
data_key = "Technical Analysis: CMO" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[cmo.info]
table = "cmo"
collection = "av_technicals"

[roc] 
function = "ROC"
[roc.format]
data_key = "Technical Analysis: ROC" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[roc.info]
table = "roc"
collection = "av_technicals"

[rocr] 
function = "ROCR"
[rocr.format]
data_key = "Technical Analysis: ROCR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[rocr.info]
table = "rocr"
collection = "av_technicals"

[aroon] 
function = "AROON"
[aroon.format]
data_key = "Technical Analysis: AROON" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[aroon.info]
table = "aroon"
collection = "av_technicals"

[aroonosc] 
function = "AROONOSC"
[aroonosc.format]
data_key = "Technical Analysis: AROONSC" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[aroonosc.info]
table = "aroonosc"
collection = "av_technicals"

[mfi] 
function = "MFI"
[mfi.format]
data_key = "Technical Analysis: MFI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[mfi.info]
table = "mfi"
collection = "av_technicals"

[trix] 
function = "TRIX"
[trix.format]
data_key = "Technical Analysis: TRIX" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[trix.info]
table = "trix"
collection = "av_technicals"

[utlosc] 
function = "ULTOSC"
[utlosc.format]
data_key = "Technical Analysis: UTLOSC" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[utlosc.info]
table = "utlosc"
collection = "av_technicals"

[dx] 
function = "DX"
[dx.format]
data_key = "Technical Analysis: DX" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[dx.info]
table = "dx"
collection = "av_technicals"

[minus_di] 
function = "MINUS_DI"
[minus_di.format]
data_key = "Technical Analysis: MINUS_DI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[minus_di.info]
table = "minus_di"
collection = "av_technicals"

[plus_di] 
function = "PLUS_DI"
[plus_di.format]
data_key = "Technical Analysis: PLUS_DI" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[plus_di.info]
table = "plus_di"
collection = "av_technicals"

[minus_dm] 
function = "MINUS_DM"
[minus_dm.format]
data_key = "Technical Analysis: MINUS_DM" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[minus_dm.info]
table = "minus_dm"
collection = "av_technicals"

[plus_dm] 
function = "PLUS_DM"
[plus_dm.format]
data_key = "Technical Analysis: PLUS_DM" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[plus_dm.info]
table = "plus_dm"
collection = "av_technicals"

[bbands] 
function = "BBANDS"
[bbands.format]
data_key = "Technical Analysis: BBANDS" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[bbands.info]
table = "bbands"
collection = "av_technicals"

[midpoint] 
function = "MIDPOINT"
[midpoint.format]
data_key = "Technical Analysis: MIDPOINT" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[midpoint.info]
table = "midpoint"
collection = "av_technicals"

[midprice] 
function = "MIDPRICE"
[midprice.format]
data_key = "Technical Analysis: MIDPRICE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[midprice.info]
table = "midprice"
collection = "av_technicals"

[sar] 
function = "SAR"
[sar.format]
data_key = "Technical Analysis: SAR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[sar.info]
table = "sar"
collection = "av_technicals"

[trange] 
function = "TRANGE"
[trange.format]
data_key = "Technical Analysis: TRANGE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[trange.info]
table = "trange"
collection = "av_technicals"

[atr] 
function = "ATR"
[atr.format]
data_key = "Technical Analysis: ATR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[atr.info]
table = "atr"
collection = "av_technicals"

[natr] 
function = "NATR"
[natr.format]
data_key = "Technical Analysis: NATR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[natr.info]
table = "natr"
collection = "av_technicals"

[ad] 
function = "AD"
[ad.format]
data_key = "Technical Analysis: AD" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ad.info]
table = "ad"
collection = "av_technicals"

[adosc] 
function = "ADOSC"
[adosc.format]
data_key = "Technical Analysis: ADOSC" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[adosc.info]
table = "adosc"
collection = "av_technicals"

[obv] 
function = "OBV"
[obv.format]
data_key = "Technical Analysis: OBV" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[obv.info]
table = "obv"
collection = "av_technicals"

[ht_trendline] 
function = "HT_TRENDLINE"
[ht_trendline.format]
data_key = "Technical Analysis: HT_TRENDLINE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_trendline.info]
table = "ht_trendline"
collection = "av_technicals"

[ht_sine] 
function = "HT_SINE"
[ht_sine.format]
data_key = "Technical Analysis: HT_SINE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_sine.info]
table = "ht_sine"
collection = "av_technicals"

[ht_trendmode] 
function = "HT_TRENDMODE"
[ht_trendmode.format]
data_key = "Technical Analysis: HT_TRENDMODE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_trendmode.info]
table = "ht_trendmode"
collection = "av_technicals"

[ht_dcperiod] 
function = "HT_DCPERIOD"
[ht_dcperiod.format]
data_key = "Technical Analysis: HT_DCPERIOD" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_dcperiod.info]
table = "ht_dcperiod"
collection = "av_technicals"

[ht_dcphase] 
function = "HT_DCPHASE"
[ht_dcphase.format]
data_key = "Technical Analysis: HT_DCPHASE" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_dcphase.info]
table = "ht_dcphase"
collection = "av_technicals"

[ht_phasor] 
function = "HT_PHASOR"
[ht_phasor.format]
data_key = "Technical Analysis: HT_PHASOR" 
first_col = "date"
transpose = true 
reset_index = true
reverse_rows = true
[ht_phasor.info]
table = "ht_phasor"
collection = "av_technicals"
