[redis]
host = "REDIS_HOST"
port = "REDIS_PORT"
password = "REDIS_PASSWORD_FILE"
[alpha-vantage]
path = "config/alpha-vantage"
url = "https://alpha-vantage.p.rapidapi.com/query"
[alpha-vantage.headers]
X-RapidAPI-Key = ["KEY_RAPIDAPI_FILE", "secret"]
X-RapidAPI-Host = ["alpha-vantage.p.rapidapi.com", "public"]

